[Downgrade] Composer's platform check must use the PHP version below
rectorphp/rector pull request #4879
Opened 2020-12-14 08:47 UTC by leoloso

When using set `downgrading-php80`, we're downgrading from PHP 8.0 to its previous version, i.e. 7.4. Hence, Composer's platform check (on `vendor/composer/platform_check.php`) must do `if (!(PHP_VERSION_ID >= 70400)) {` (not `80000`).

Fixed for all downgrade sets.

2020-12-14 09:13 UTC, simivar requested changes

2020-12-14 09:13 UTC, simivar commented on rules/symfony5/src/Rector/New_/PropertyAccessorCreationBooleanToFlagsRector.php
> +    private function shouldSkip(New_ $new): bool
Changes for this file seem out of the scope of this PR.

2020-12-14 09:15 UTC, simivar requested changes

2020-12-14 09:15 UTC, simivar commented on rules/symfony5/src/Rector/New_/PropertyAccessorCreationBooleanToFlagsRector.php
> +        $classConstFetch = $this->createClassConstFetch(
Name `classConstFetch` can be misleading as we have multiple of them created here (one line below we have `magicSet` for example).

2020-12-14 09:27 UTC, leoloso commented
@simivar all these unsuitable changes were applied automatically by Rector Rectify: https://github.com/rectorphp/rector/pull/4879/commits/182aef1bbc73966ce3ee74ec951988c52d42fdde

That's why this is happening in all my PRs!

If this is bug, I can create a new issue about it...

2020-12-14 16:28 UTC, TomasVotruba commented
> If this is bug, I can create a new issue about it...


It is indeed unrleated to PR. Please create failing test case for the broken rule

2020-12-14 16:29 UTC, merged

2020-12-14 16:29 UTC, TomasVotruba commented
Thank you

2020-12-15 06:53 UTC, leoloso commented
> Please create failing test case for the broken rule

There's no broken rule. It's just Rector Rectify working properly, on 1 file (for rule `PropertyAccessorCreationBooleanToFlagsRector`) that, somehow, had not been previously rectified...

I guess when this happens again, we can switch to master, and do some simple change just to trigger Rector Rectify, and commit the rectified code so it doesn't spill over the other PRs

2020-12-15 07:43 UTC, TomasVotruba commented
The rule can do better. It should be fixed now, because it changes our code for worse

2020-12-15 08:24 UTC, leoloso commented
Ok, hopefully I get it now. The problem is that if there are 2 or more variables (`$magicGet` and `$magicSet`) that can be renamed to the same name (as `$classConstFetch`), then the rule should be skipped...

Then, `$flags` renamed as `$bitwiseOr`, that's OK.

Is this right?

2020-12-15 08:38 UTC, TomasVotruba commented
Yes, exactly.

2020-12-15 15:08 UTC, leoloso commented
Added now in #4898. But I wonder if I got it right? The tests are failing in a different way to Rector Rectify's behavior...